### ISSUE TITLE
Too common name?

### ISSUE THREAD

**Issue by qrilka** [Yuras/scanner#1]
The parser seems to be quite specific in parsing only bytestring and with no backtracking and still "Scanner" looks to be very common term, wouldn't it be better to use some more unique name for it? Especially taking into account the fact of using top-level module with such a common name.
Of course I'm only speculating here but it could be at least inconvenient for some projects.

**Comment by Yuras** [comment]
Well, I don't know. We have `-XPackageImports` anyway. I always thought that prefixes like `Data`, `Control`, `Graphics` etc are ugly and unnecessary, but it is just an opinion. Having top level module name to be the same as package name seems reasonable for me.

Re package name, I think scanner perfectly reflects non-backtracking nature of the parser. Image scanner never goes back to rescan the already scanned area. And it is basically what `scan` from attoparsec does: https://hackage.haskell.org/package/attoparsec-0.13.0.1/docs/Data-Attoparsec-ByteString.html#v:scan

I have plans (not immediate though) to extend the package to work with `Text` and probably other containers. Probably `Scanner.ByteString` module name will work better in that case. I'm not sure actually.

**Comment by qrilka** [comment]
If you have no plans to change the name then probably you should close the issue as "won't fix" :)

**Comment by Yuras** [comment]
OK, lets close it for now. But I certainly should think about module name.
Thank you.
