### ISSUE TITLE
relation to cereal/binary?

### ISSUE THREAD

**Issue by winterland1989** [Yuras/scanner#5]
What's the relation between this library and cereal/binary? the internals seems quite similar, I'd like to see some work on this library get merged back to cereal/binary(`takeWhile/takeTill...`), but maybe you intend to do something different here?

**Comment by Yuras** [comment]
IIRC `cereal` and `binary` support backtracking. `scanner` doesn't support backtracking for performance reasons, so I don't think there is anything to share with cereal/binary.

The library was designed for fast non-backtracking parsing, like [json parser](https://github.com/Yuras/scanner-json) (2x faster then aeson for me)

**Comment by winterland1989** [comment]
I see, so is there any plan to support more low level operations? such as `getWordXX`/`getWordXXBE`, i'm search for a fast binary decoder to deal with a network protocol, backtracking is not necessary, but some helpers to deal with machine format is needed.

**Comment by Yuras** [comment]
I'm happy to add `getWordXX` etc. Feel free to PR if you want it to happen sooner.

Though I don't think `getWordXX` is low level, it could be implemented using `take` or `anyWord8`.

**Comment by winterland1989** [comment]
Ok, i guess i'd like to build a binary encode/decode library on top of scanner with cereal/binary like APIs so that i can easily migrate old code,  (maybe add a bunch of `Generic/TH` stuff i suppose). Thanks for your code!

BTW, I'll try to make a patch for aeson using `Scanner`, because i'm not satisfy with its performance as well, using attoparsec is completely wasteful there.
